title: Hypertension Treatment Response Predictions
description: Healthcare Analytics Portfolio Project
author: Ryan Goodwin
remote_theme: pages-themes/cayman@v0.2.0
domain: goodwin282.github.io
url: https://goodwin282.github.io
baseurl: "/hypertension-treatment-response-prediction"

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# GitHub Pages specific settings
github:
  is_project_page: true
  repository_name: hypertension-treatment-response-prediction